### ISSUE TITLE
User Interface Differences

### ISSUE THREAD

**Issue by softwareangel** [Kathy-Lueckeman/EASY-Open-Source-Solution#5]
Greetings,

According to the images in the EASY User Guide, the user interface has a back/next arrows with a 
"Save" button at the bottom. 

User Guide Interface:
![image](https://user-images.githubusercontent.com/45464122/49287582-0c9c1100-f46c-11e8-906b-88d47bb82774.png)

After creating the example described the EASY User Guide: THE APPLICATION EXPERIENCE (section), my interface has a back/next with the save button displaying at the end of the application.  I was under the impression the application could be saved for later editing.  Is this still the case? 

Test Application:
![image](https://user-images.githubusercontent.com/45464122/49287633-44a35400-f46c-11e8-8b28-bf22a05119d8.png)

I have tested this in Firefox, Chrome and IE 11, which produced the same experience with back/next buttons instead of arrows.  Is there a special configuration or Visualforce page that controls the button placement and functionality? If there was a design change, please update the documentation.

I would appreciate any assistance on this issue.  Thanks.

**Comment by kyleschmid** [comment]
@softwareangel The documentation has out of date screenshots for the back/next buttons. We made the decision to change them to actual buttons instead of arrows to make things more clear.

And yes, you can get back to the application after you start it. Anything marked "Show on Application Creation" will show up to start a new application to begin with. Once you start one, it will take you to the checklist page where you can fill out more requirements that can be saved/returned to.
